workflow: spatial

params:
  begin: host
  samples: sample.tsv
  project: 
  
  host:
    spaceranger:
      do: true
      reference: "/path/to/spaceranger/reference"
      # Spaceranger specific parameters
      image_params:
        reorient-images: true
        unknown-slide: true
      probe_set: ""
      variousParams: ""

  classifier:
    kraken2uniq:
      do: true
      kraken2_database: "/path/to/kraken2_database"
      minimum_hit: 3
      confidence: 0
      variousParams: ""

  align:
    download_dir: ""
    bowtie2:
      do: true
      db: ""
    bwa:
      do: false
      db: ""
    bwa2:
      do: false
      db: ""
    minimap2:
      do: false
      db: ""

output:
  raw: results/00.raw
  host: results/02.host
  classifier: results/03.classifier

logs:
  prepare: "logs/00.prepare"
  host: "logs/02.host"
  classifier: "logs/03.classifier"

benchmarks:
  host: "benchmarks/02.host"
  classifier: "benchmarks/03.classifier"

envs:
  kraken2: ../envs/kraken2.yaml
  star: ../envs/star.yaml
  bwa2: ../envs/bwa2.yaml

resources:
  spaceranger:
    threads: 20
    mem_mb: 100000
  samtools_extract:
    threads: 20
    mem_mb: 40000
  kraken2uniq:
    threads: 20
    mem_mb: 120000

scripts:
  extract_kraken_output: scripts/extract_kraken_output.py
  extract_kraken_bam: scripts/extract_kraken_bam.py
  kraken2mpa: scripts/kraken2mpa.py
  extract_kraken_reads: scripts/extract_kraken_reads.py
  preprocess_raw: scripts/preprocess_raw.py
