# Modified from https://jupyterbook.org/en/stable/publish/gh-pages.html
name: Build documentation and deploy

on:
  push:
    # Only build the docs when a push is made to the main branch and the docs folder is changed
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install jupyter-book

      # Build the book
      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter-book build docs/

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html